---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Create Network
      cisco.meraki.networks:
        state: present
        organizationId: "355089"
        name: Made With Ansible networks
        notes: Made_with_anisble
        productTypes:           
          - switch
          - appliance
          - wireless
        timeZone: Australia/Sydney